[package]
name = "lightgbm-example-regression"
version = "0.1.0"
authors = ["vaaaaanquish <6syun9@gmail.com>"]
publish = false

[dependencies]
lightgbm2 = { path = "../../" }
csv = "1.1.5"
itertools = "0.10"
serde_json = "1.0.59"
